export const site = {name:'Florida Flamingo Working Group', legalName:'Florida Flamingo Working Group, Inc.', description:'Research, conservation, and collaboration for wild American flamingos and the Florida wetlands they depend on.', donation:'https://www.paypal.com/donate/?hosted_button_id=4PF69PGSCR5FN'};
export const paths = ['','about-us','our-work','why-flamingos-matter','research-and-resources','sightings-map','report-a-flamingo-sighting','state-bird-campaign','news','get-involved','contact-us','privacy'];
export const navigation = [['Our work','/our-work/'],['Sightings map','/sightings-map/'],['The science','/research-and-resources/'],['About us','/about-us/'],['Get involved','/get-involved/']];
export const research = [
{year:'2018',topic:'Historical ecology',title:'Status and trends of American Flamingos in Florida, USA',author:'Whitfield et al. · The Condor 120:291–304',text:'Historical accounts, museum specimens, and modern sightings provide a scientific foundation for understanding the flamingo’s native status in Florida.',href:'https://doi.org/10.1650/CONDOR-17-187.1'},
{year:'2021',topic:'Movement & habitat',title:'Satellite telemetry in Florida Bay',author:'Whitfield et al. · Florida Field Naturalist 49(2)',text:'A 22-month study followed one wild flamingo across tidal flats and mangrove-fringed mudflats. Its findings illuminate habitat use, with the limitations of a single-bird study.',href:'https://digitalcommons.usf.edu/ffn/vol49/iss2/6/'},
{year:'2020',topic:'Range & distribution',title:'Distribution, trends, and important breeding areas',author:'Torres-Cristiani et al. · PLOS ONE 15(12)',text:'Community-science records help describe the species’ range across the Americas. Reporting effort and actual bird numbers must be considered separately.',href:'https://doi.org/10.1371/journal.pone.0244117'},
{year:'2025 / 26',topic:'Population genetics',title:'Spatial and temporal population genomics',author:'Folsom et al. · Ornithological Applications',text:'Historical and contemporary samples inform questions about genetic diversity, population connections, and potential recovery options. Online publication: 2025; journal issue: 2026.',href:'https://doi.org/10.1093/ornithapp/duaf071'}
];
export const leadership = [{role:'President',name:'Dr. Steven Whitfield',affiliation:'Audubon Nature Institute'},{role:'Vice President',name:'Dr. Jerry Lorenz',affiliation:'Florida International University'},{role:'Secretary',name:'Dr. Mark Cook',affiliation:'South Florida Water Management District'},{role:'Treasurer',name:'Tony Pernas',affiliation:'National Park Service, Retired'}];
