import Link from 'next/link';
import Image from 'next/image';
import {Photo,TakePart} from '@/components/UI';
import {research} from '@/content/site';
export const metadata={alternates:{canonical:'/'}};
export default function Home(){return <>
<section className="hero"><Image src="/images/original-9.webp" alt="A group of American flamingos wading in pale blue shallow water" fill sizes="100vw" priority/><div className="hero-shade"/><div className="container hero-content"><p className="eyebrow">SCIENCE. CONSERVATION. COLLABORATION.</p><h1>Florida’s flamingos<br/>are coming back.</h1><p className="hero-sub">We’re working to help them stay.</p><p className="hero-description">Protecting a native icon means understanding its story—and safeguarding the wild places its future depends on.</p><div className="actions"><Link className="button coral" href="/our-work/">Explore our work <span aria-hidden="true">↗</span></Link><Link className="hero-link" href="/report-a-flamingo-sighting/">Report a flamingo sighting <span aria-hidden="true">→</span></Link></div></div><div className="hero-caption">AMERICAN FLAMINGO <span> / </span> <i>Phoenicopterus ruber</i></div></section>
<section className="intro-strip"><div className="container"><span>A NATIVE SPECIES.<br/>A SHARED RESPONSIBILITY.</span><p>We bring together scientists, wildlife professionals, educators, and communities to conserve American flamingos in Florida and across the Caribbean.</p><Link href="/about-us/" aria-label="Meet the Florida Flamingo Working Group">Meet the group ↗</Link></div></section>
<section className="section container story-grid"><div><p className="eyebrow">THE FLORIDA STORY</p><h2>More than an icon.<br/><em>One of our own.</em></h2><p className="lead">Long before the postcards, flamingos belonged to Florida.</p><p>Historical accounts and museum records document a native bird once seen in large flocks. Hunting helped drive that population from the state around the turn of the twentieth century.</p><p>Today, naturally arriving flamingos are part of a renewed chapter. Research helps us understand their movements—and what a lasting recovery will require.</p><Link className="text-link" href="/research-and-resources/">Discover the evidence <span aria-hidden="true">↗</span></Link><p className="source-note">Source: <a href="https://myfwc.com/wildlifehabitats/profiles/birds/waterbirds/american-flamingo/">Florida Fish and Wildlife Conservation Commission</a>; Whitfield et al. (2018).</p></div><div className="story-image"><Photo src="/images/original-2.webp" alt="Two American flamingos feeding with their bills in shallow water"/><div className="image-note"><span>NATIVE TO FLORIDA</span><p>A familiar symbol.<br/>An extraordinary wild bird.</p></div></div></section>
<section className="facts-band"><div className="container facts"><div><span>Native</span><p>Recognized by Florida’s wildlife agency</p></div><div><span>Connected</span><p>Part of a wider Caribbean population story</p></div><div><span>22 months</span><p>One Florida Bay flamingo tracked in a field study</p></div></div></section>
<section className="section container"><div className="section-heading"><div><p className="eyebrow">FROM EVIDENCE TO ACTION</p><h2>Working for a wild future.</h2></div><Link className="text-link" href="/our-work/">All of our work ↗</Link></div><div className="work-cards"><Link href="/our-work/#monitoring" className="work-card"><Photo src="/images/original-4.webp" alt="Aerial view of flamingos scattered across shallow wetland habitat"/><div><span className="eyebrow">01 / MONITOR</span><h3>Follow the flamingos.</h3><p>Sightings, photographs, and field observations help reveal where birds are and how they move.</p><span className="card-link">Population monitoring ↗</span></div></Link><Link href="/research-and-resources/" className="work-card"><Photo src="/images/original-8.webp" alt="Two American flamingos in flight"/><div><span className="eyebrow">02 / UNDERSTAND</span><h3>Let science lead.</h3><p>From historical records to genomics, research builds the foundation for conservation decisions.</p><span className="card-link">Explore the research ↗</span></div></Link><Link href="/why-flamingos-matter/" className="work-card"><Photo src="/images/original-3.webp" alt="Flamingos gathered along a wetland edge, seen from above"/><div><span className="eyebrow">03 / CONSERVE</span><h3>Protect the places.</h3><p>Healthy wetlands, estuaries, and coastal habitats support flamingos and a wider world of wildlife.</p><span className="card-link">Why wetlands matter ↗</span></div></Link></div></section>
<section className="habitat"><Photo src="/images/original-0.webp" alt="Flamingos flying above coastal water beside mangroves"/><div className="habitat-copy"><p className="eyebrow">A BIGGER PICTURE</p><h2>For the birds.<br/>For the wetlands.<br/><em>For Florida.</em></h2><p>Wetlands provide wildlife habitat, help filter water, store carbon, and buffer flooding. Understanding how flamingos use these places can help inform their protection.</p><Link className="text-link" href="/why-flamingos-matter/">See the connections ↗</Link></div></section>
<section className="section container research-home"><div><p className="eyebrow">THE SCIENCE BEHIND THE STORY</p><h2>Curiosity.<br/>Evidence.<br/>Conservation.</h2><Link className="text-link" href="/research-and-resources/">Visit the research library ↗</Link></div><div>{research.slice(0,3).map(r=><a href={r.href} className="research-row" key={r.href}><span>{r.year}</span><div><p className="eyebrow">{r.topic}</p><h3>{r.title}</h3><p>{r.author}</p></div><span aria-hidden="true">↗</span></a>)}</div></section>
<section className="campaign-teaser container"><div><p className="eyebrow">OUR STATE BIRD CAMPAIGN</p><h2>Native. Iconic.<br/>Unmistakably Florida.</h2><p>We support recognizing the American flamingo as Florida’s official state bird. Learn about the campaign, its history, and how to take part.</p><Link className="button navy" href="/state-bird-campaign/">Explore the campaign ↗</Link></div><Photo src="/images/original-6.webp" alt="Pink flamingos standing in calm, pale blue water"/></section><TakePart/>
</>}
