import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import Markdown from 'react-markdown';
import pages from '@/content/pages.json';
import members from '@/content/members.json';
import {leadership,paths,research,site} from '@/content/site';
import {PageIntro,Photo,TakePart} from '@/components/UI';
import SubmissionForm from '@/components/SubmissionForm';
const copy:Record<string,[string,string,string]>={
'about-us':['WHO WE ARE','Science brings us together.','A shared commitment to the conservation and recovery of American flamingos in Florida and throughout their range.'],
'our-work':['RESEARCH INTO ACTION','Understand. Protect. Recover.','Connecting field observations, scientific research, habitat conservation, and public stewardship.'],
'why-flamingos-matter':['A CONNECTED LANDSCAPE','A bird. A habitat. A shared future.','The flamingo’s story is also the story of Florida’s shallow waters, coastal ecosystems, and natural heritage.'],
'research-and-resources':['THE EVIDENCE','Research & resources','Explore the science behind Florida’s flamingos—from historical records to movements, habitat, and population genetics.'],
'report-a-flamingo-sighting':['CONTRIBUTE TO THE SCIENCE','Report a flamingo sighting','A careful observation can help researchers better understand the distribution and movements of American flamingos.'],
'state-bird-campaign':['FFWG ADVOCACY','Native. Iconic. Unmistakably Florida.','We support recognizing the American flamingo as Florida’s official state bird.'],
'news':['FROM THE WORKING GROUP','News & updates','Research, conservation, and campaign developments.'],
'get-involved':['A SHARED RESPONSIBILITY','There’s a place for you.','You don’t have to be a scientist to contribute to a future with wild flamingos.'],
'contact-us':['LET’S CONNECT','Contact the working group','We welcome research collaborations, media inquiries, education opportunities, and questions about our work.'],
'privacy':['YOUR INFORMATION','Privacy & responsible reporting','A clear explanation of how information is handled on this website.']};
export function generateStaticParams(){return paths.filter(Boolean).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const c=copy[slug];return c?{title:c[1],description:c[2],alternates:{canonical:`/${slug}/`},openGraph:{title:c[1],description:c[2],url:`/${slug}/`}}:{};}
function Prose({children}:{children:string}){return <div className="prose"><Markdown components={{h2:({children})=><h2 id={String(children).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}>{children}</h2>}}>{children}</Markdown></div>}
const get=(slug:string)=>(pages as Record<string,{body:string}>)[slug].body;
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!copy[slug])notFound();const [eyebrow,title,description]=copy[slug];let content;
if(slug==='about-us'){const body=get(slug);content=<><section className="container section about-top"><Prose>{body.split('## Leadership')[0]}</Prose><aside><Photo src="/images/original-10.webp" alt="American flamingos of different ages gathered in shallow water"/><div className="aside-note"><p className="eyebrow">OUR MISSION</p><p>Conserve American flamingos through research, habitat protection, population recovery, education, and collaboration.</p></div></aside></section><section className="soft section"><div className="container"><p className="eyebrow">PEOPLE BEHIND THE WORK</p><h2>Our leadership</h2><div className="leader-grid">{leadership.map(l=><article className="leader" key={l.role}><p className="eyebrow">{l.role}</p><h3>{l.name}</h3><p>{l.affiliation}</p></article>)}</div><h2 className="members-title">Working group members</h2><p>Our members bring experience in wildlife research, wetland ecology, natural-resource management, conservation, and education.</p><p className="source-note">Affiliations identify members’ professional connections. Participation does not imply an institution’s formal endorsement.</p><div className="member-grid">{members.map(m=><div key={m.name}><h3>{m.name}</h3><p>{m.affiliation}</p></div>)}</div></div></section><section className="container section narrow"><Prose>{'## Working Beyond Borders'+body.split('## Working Beyond Borders')[1]}</Prose><Link className="button navy" href="/get-involved/">Find your way to contribute ↗</Link></section></>;}
else if(slug==='our-work'){const sections=get(slug).split('## ').filter(Boolean);content=<><section className="container section"><div className="work-detail-grid">{sections.map((s,i)=>{const [heading,...body]=s.split('\n');return <article className="work-detail" key={heading} id={i===0?'monitoring':`work-${i}`}><span className="section-number">0{i+1}</span><h2>{heading}</h2><Prose>{body.join('\n').replace('This designation will','This designation could')}</Prose></article>})}</div></section><section className="wide-photo container"><Photo src="/images/original-8.webp" alt="Two flamingos flying with wings extended"/></section><TakePart/></>;}
else if(slug==='why-flamingos-matter'){content=<><section className="container section story-grid"><div><p className="eyebrow">THE HABITAT CONNECTION</p><h2>Wildlife needs<br/><em>healthy places.</em></h2><p className="lead">Where flamingos feed, rest, and gather can tell us more about the places they use.</p><p>Research into flamingo movements and habitat use helps identify important shallow-water feeding and resting areas. It can inform where protection, restoration, and further study may be needed.</p><p>A sighting alone is not a water-quality measurement or proof of ecosystem recovery. Careful monitoring puts individual observations into context.</p><a className="text-link" href="https://digitalcommons.usf.edu/ffn/vol49/iss2/6/">Read the Florida Bay field study ↗</a></div><Photo src="/images/original-3.webp" alt="An aerial view of flamingos using a shallow wetland"/></section><section className="soft section"><div className="container"><p className="eyebrow">WHY WETLANDS MATTER</p><h2>Benefits that reach beyond the birds.</h2><div className="benefit-grid">{[['Wildlife habitat','Wetlands and estuaries provide food, shelter, and nursery habitat for birds, fish, and other wildlife.'],['Water quality','Wetland vegetation, soils, and natural processes can help retain sediments and improve water quality.'],['Coastal resilience','Wetlands can store floodwaters, slow their movement, and reduce shoreline erosion.'],['Carbon storage','Wetland soils and plant communities store carbon, connecting local habitat protection to wider climate processes.'],['Connected habitats','Mangroves, mudflats, estuaries, and shallow coastal water form a varied landscape for flamingos and other species.'],['Florida’s heritage','Conserving these places supports recreation, coastal livelihoods, and a distinctive part of Florida’s natural identity.']].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div><p className="source-note">Wetland functions vary by location and condition. Sources: <a href="https://www.epa.gov/wetlands/why-are-wetlands-important">U.S. Environmental Protection Agency</a> and <a href="https://digitalcommons.usf.edu/ffn/vol49/iss2/6/">Whitfield et al. (2021)</a>.</p></div></section><TakePart/></>;}
else if(slug==='research-and-resources'){const body=get(slug);content=<><section className="container section"><div className="native-callout"><p className="eyebrow">START HERE</p><h2>Are flamingos native to Florida?</h2><p>Yes. The Florida Fish and Wildlife Conservation Commission recognizes the American flamingo as native. Historical accounts, museum specimens, and modern observations help explain its place in Florida.</p><a className="text-link" href="https://myfwc.com/wildlifehabitats/profiles/birds/waterbirds/american-flamingo/">Read the FWC species profile ↗</a></div><div className="section-heading"><h2>Featured research</h2><span className="eyebrow">PEER-REVIEWED PUBLICATIONS</span></div><div className="publication-grid">{research.map(r=><article key={r.href}><span className="tag">{r.topic} · {r.year}</span><h3>{r.title}</h3><p className="citation">{r.author}</p><p>{r.text}</p><a className="text-link" href={r.href}>Read the study ↗</a></article>)}</div></section><section className="soft section"><div className="container narrow"><Prose>{'## Research Priorities'+body.split('## Research Priorities')[1].split('## Featured Research')[0]}</Prose></div></section><section className="container section narrow"><Prose>{'## Species and Conservation Resources'+body.split('## Species and Conservation Resources')[1]}</Prose><p className="source-note">Research summaries describe published findings. University summaries and species profiles are identified separately from the papers themselves.</p></section></>;}
else if(slug==='state-bird-campaign'){const body=get(slug);content=<><section className="container section campaign-layout"><aside><Photo src="/images/original-2.webp" alt="Two American flamingos feeding in shallow water"/><div className="status-box"><p className="eyebrow">2026 SESSION • VERIFIED SEPTEMBER 17</p><h2>The campaign continues.</h2><p>HB 11 and SB 150 did not become law. The northern mockingbird remains Florida’s official state bird.</p><a href="https://www.flsenate.gov/Session/Bill/2026/11">HB 11 legislative record ↗</a><a href="https://www.flsenate.gov/Session/Bill/2026/150">SB 150 legislative record ↗</a></div></aside><Prose>{body.replace('## Native. Iconic. Unmistakably Florida.','').replace('Senate Bill 150 received unanimous approval from the Senate Committee on Environment and Natural Resources but later died in committee.','Senate Bill 150 received a 6–0 vote from the Senate Committee on Environment and Natural Resources, then died in the Appropriations Committee on Agriculture, Environment, and General Government on March 13, 2026.')}</Prose></section></>;}
else if(slug==='report-a-flamingo-sighting'||slug==='contact-us'){const sighting=slug==='report-a-flamingo-sighting';content=<section className="container section form-layout"><div><SubmissionForm kind={sighting?'sighting':'contact'} live={process.env.FORMS_ENABLED==='true'&&!!process.env.FORM_WEBHOOK_URL&&!!process.env.FORM_WEBHOOK_SECRET}/></div><aside className="form-aside">{sighting?<><p className="eyebrow">PUT THE BIRDS FIRST</p><h2>A good sighting leaves no trace.</h2><ul><li>Remain at a respectful distance.</li><li>Do not approach, follow, feed, or flush birds.</li><li>Use binoculars or a telephoto lens.</li><li>Keep dogs controlled and away from wildlife.</li><li>Follow posted access restrictions.</li><li>Record bands or tags only if visible from where you are.</li><li>Avoid posting precise locations of vulnerable birds publicly.</li></ul><p>Exact locations are for research and conservation and will not be publicly disclosed without permission.</p><Photo src="/images/original-6.webp" alt="Flamingos standing together in calm water"/></>:<><p className="eyebrow">SAW A FLAMINGO?</p><h2>Help put it on the research map.</h2><p>Use our dedicated sighting form so researchers have the date, location, number of birds, and other useful details.</p><Link className="text-link" href="/report-a-flamingo-sighting/">Report a sighting ↗</Link><h3>Your privacy</h3><p>Your contact information is used to respond to your inquiry or provide updates you request. We will not publicly share it.</p></>}<Link href="/privacy/">Read our privacy information</Link></aside></section>;}
else if(slug==='get-involved'){content=<><section className="container section"><div className="involvement-grid">{[['01','Share a sighting','Document the date, place, number of birds, and visible bands or tags. Photographs can help researchers evaluate an observation.','Report a sighting','/report-a-flamingo-sighting/'],['02','Observe responsibly','Keep your distance, respect access restrictions, and let birds feed and rest undisturbed.','Read observation guidance','/research-and-resources/#responsible-observation'],['03','Collaborate with us','Researchers, institutions, educators, and conservation organizations can ask about sharing knowledge and contributing to our work.','Start a conversation','/contact-us/'],['04','Support the work','The existing FFWG donation page accepts contributions through PayPal to support the organization’s conservation mission.','Donate through PayPal',site.donation],['05','Add your voice','Learn about the state bird campaign and share accurate information about the American flamingo’s history in Florida.','Explore the campaign','/state-bird-campaign/'],['06','Stay connected','Ask about participation, volunteer opportunities, educational resources, and future working-group updates.','Contact the group','/contact-us/']].map(([n,h,p,l,u])=><article key={n}><span className="section-number">{n}</span><h2>{h}</h2><p>{p}</p><Link className="text-link" href={u}>{l} ↗</Link></article>)}</div></section><TakePart/></>;}
else if(slug==='news'){content=<section className="container section"><div className="news-grid"><article><p className="eyebrow">LEGISLATIVE HISTORY · MARCH 13, 2026</p><h2>The 2026 state bird proposals</h2><p>HB 11 and SB 150 did not receive final approval. Read the documented legislative history and learn why the FFWG campaign continues.</p><Link className="text-link" href="/state-bird-campaign/">Read the campaign update ↗</Link></article><article><p className="eyebrow">RESEARCH · DECEMBER 18, 2025</p><h2>A new view of flamingo genetics</h2><p>A UCF research summary explores genetic diversity, connections among populations, and questions for future restoration.</p><a className="text-link" href="https://www.ucf.edu/news/ucf-study-confirms-flamingos-are-native-to-florida-and-genetically-fit-for-restoration/">Read the university’s article ↗</a></article></div><div className="updates-note"><h3>More from the working group</h3><p>Research updates, survey results, meetings, events, and announcements will be shared here as they are published.</p><Link href="/contact-us/">Ask about upcoming activities ↗</Link></div></section>;}
else{content=<section className="container section narrow prose"><h2>During website review</h2><p>Forms on this preview are demonstrations unless explicitly marked as ready to receive submissions. In demonstration mode, entries and selected photographs remain in your browser’s memory and are not submitted or stored. Closing or refreshing the page clears them.</p><p>For a real sighting or inquiry during review, follow the clearly labeled link to the organization’s existing website. Its own form service handles those submissions.</p><h2>When submission delivery is enabled</h2><p>Sighting information is used for research and conservation. Exact locations are not publicly disclosed without permission. Personal contact information is not publicly shared. Contact inquiries are used to respond to you or provide updates you specifically request.</p><p>The form separately asks whether submitted information and photographs may be used for education and outreach. Do not include information about other people without their permission.</p><h2>Website services</h2><p>The website is hosted on Vercel, which may process standard request information to deliver and secure the site. No advertising trackers or optional analytics are installed. Photographs displayed on this site are served with the website.</p><h2>External services</h2><p>Links to PayPal, research publishers, agencies, and the existing FFWG website take you to independently operated services with their own privacy practices.</p><h2>Questions and requests</h2><p><Link href="/contact-us/">Contact the working group</Link> about privacy, corrections, or removal of submitted information. Final retention periods and the organization’s submission processor must be confirmed before live collection begins.</p></section>;}
return <><PageIntro eyebrow={eyebrow} title={title} description={description}/>{content}</>;}
